# Generated by Django 4.1.4 on 2022-12-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('M-PESA', 'M-PESA'), ('CASH', 'CASH')], default='CASH', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
